### PR TITLE
0.13.2 h6af634

### PR DESCRIPTION
**Pull request by bryanwweber**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Supersedes #13

### CODE REVIEW

**Comment by bryanwweber** [comment]
Blocked on https://github.com/conda-forge/sphinx-togglebutton-feedstock/pull/4

**Comment by mmcky** [comment]
thanks @bryanwweber

**Comment by bryanwweber** [comment]
@conda-forge-admin, please rerender

**Comment by bryanwweber** [comment]
@conda-forge-admin, please rerender

**Comment by bryanwweber** [comment]
@mmcky this is good to go now 😊

**Comment by mmcky** [comment]
thanks @bryanwweber

**Pull request merged**
